### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PnsDev** [2lstudios-mc/ViaPotions#10]
The error occurs when starting
```
[16:51:53 INFO]: Enabling ViaPotions v0.0.3
[16:51:53 ERROR]: No compatible plugins have been detected, disabling the plugin.
[16:51:53 ERROR]: In order to make ViaPotions functional, ViaRewind must be installed.
[16:51:53 INFO]: Disabling ViaPotions v0.0.3
```
I have ProtocolSupport (1.16.5-3) and ProtocolLib (4.7.0) installed.

**Comment by linsaftw** [comment]
We don't support ProtocolSupport anymore, only ViaRewind. We did this because the latest versions wasn't compiling.

**Comment by PnsDev** [comment]
> We don't support ProtocolSupport anymore, only ViaRewind. We did this because the latest versions wasn't compiling.

What was the version supported in e5c95fe?

**Comment by linsaftw** [comment]
> > We don't support ProtocolSupport anymore, only ViaRewind. We did this because the latest versions wasn't compiling.
> 
> What was the version supported in [e5c95fe](https://github.com/2lstudios-mc/ViaPotions/commit/e5c95fea9d2c82d44087e79e46ea0466aca67de7)?

I don't know but it requires Java 16, doesn't have official maven repo and it's slow. There is no reason to run ProtocolSupport anymore as ViaRewind/ViaBackwards does a better job.
