### ISSUE TITLE
Can't use getWorld for temporary players.

### ISSUE THREAD

**Issue by awgybop1** [2lstudios-mc/ViaPotions#6]
I'm sure this all you need, but I can post more if needed.

```
[ViaPotions] Unhandled exception occured in onPacketSending(PacketEvent) for ViaPotions
java.lang.UnsupportedOperationException :: The method getWorld is not supported for temporary players.
```

**Comment by linsaftw** [comment]
Make sure you are using latest protocollib version & viapotions version.

https://github.com/2lstudios-mc/ViaPotions/blob/master/src/dev/_2lstudios/viarewindpotions/adapters/WorldEventAdapter.java

We aren't using any getWorld() methods.

What is your server version?

**Comment by linsaftw** [comment]
Fixed now. Thank you for reporting and sorry for the delay.
